<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9hhadlk\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9hhadlk/appProdProjectContainer.php') {
    touch(__DIR__.'/Container9hhadlk.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container9hhadlk\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container9hhadlk\appProdProjectContainer(array(
    'container.build_hash' => '9hhadlk',
    'container.build_id' => '13f5d36b',
    'container.build_time' => 1643567711,
), __DIR__.\DIRECTORY_SEPARATOR.'Container9hhadlk');
