<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerD8wtpei\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerD8wtpei/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerD8wtpei.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerD8wtpei\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerD8wtpei\appDevDebugProjectContainer(array(
    'container.build_hash' => 'D8wtpei',
    'container.build_id' => 'd23b4952',
    'container.build_time' => 1643567589,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerD8wtpei');
